server:
  port: ${PORT:8888}
  servlet:
    context-path: /api

spring:
  profiles:
    active: dev

  main:
    web-application-type: servlet
  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 500MB
      max-request-size: 510MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls: #encrypted
            enable: true
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:5173}


#file
file:
  upload:
    base-path:
      lesson-resources: "${user.dir}/src/main/resources/upload/lesson_resources"
      assignment-submissions: "${user.dir}/src/main/resources/upload/assignment-submissions/"
      assignment-attachments: "${user.dir}/src/main/resources/upload/assignment-attachments/"
      library-resources: "${user.dir}/src/main/resources/upload/library_resources/"
      library-covers: "${user.dir}/src/main/resources/upload/library_covers/"
      lesson-videos: "${user.dir}/src/main/resources/upload/lesson_videos"
